### ISSUE TITLE
performance data

### ISSUE THREAD

**Issue by fwz-fpga** [google/ruy#270]
Is there any performance data about ruy? 
Compare with gemmlowp or other optimize lib. I see that tflite use gemmlowp and ruy both. Which is better in performance.

**Comment by bjacob** [comment]
This spreadsheet has such data. The '8bit' sheets are comparing against gemmlowp.
https://docs.google.com/spreadsheets/d/1CB4gsI7pujNRAf5Iz5vuD783QQqO2zOu8up9IpTKdlU/edit?usp=sharing

**Comment by fwz-fpga** [comment]
> This spreadsheet has such data. The '8bit' sheets are comparing against gemmlowp.
> https://docs.google.com/spreadsheets/d/1CB4gsI7pujNRAf5Iz5vuD783QQqO2zOu8up9IpTKdlU/edit?usp=sharing

thanks!! 
I think we will use ruy replace gemmlowp.
But another question : (  I build from source use cmake and found it generate a lot of static libs. Such as libruy_kernel_avx512.a libruy_kernel_avx.a libruy_frontend.a.
If I use ruy on arm platform, how can I only build arm related libs.

**Comment by bjacob** [comment]
The architecture-specific static libraries like `libruy_kernel_avx512.a` are nearly empty when the actual build architecture is not the one that they are relevant to (e.g. x86 libraries are empty on ARM).  They will only contain empty functions, or, when assertions are enabled, they will only contain a false-assertion ensuring that these functions are never called:
https://github.com/google/ruy/blob/22f89228893b3abae601004a6e48b64e089fc626/ruy/kernel_avx.cc#L33-L55

Note, anyway, that x86-specific code simply wouldn't compile when the target architecture is ARM.

So you should be able to ignore all this as an internal implementation detail of ruy. You can always assess what symbols are in your final binary by using the `nm` command from your ARM toolchain, e.g.

```
$HOME/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-nm --radix=d -S -C $HOME/ruy-build/ruy/example/parametrized_example | grep 'ruy::' | awk '{sum+=$2} END {print sum}'
```

(`parametrized_example` in the `example` directory is a simple way to assess overall ruy code size as it instantiates many different `ruy::Mul` template instantiations - actual applications would see *smaller* ruy code because they instantiate fewer).
