### ISSUE TITLE
Why is the result zero？

### ISSUE THREAD

**Issue by GitEasonXu** [google/ruy#312]
I have two matrices: A=[[1,2], [3,4]]  B=[[1,3],[2,4]], but the result AB is zero matrix [[0,0], [0,0]].
I don't know how `ruy::Mul` works. Is there any avalibe information? Thanks!!

```
void ExampleMulInt8PerChannelQuantized(ruy::Context *context) {
  const std::int8_t lhs_data[] = {1, 2, 3, 4};
  const std::int8_t rhs_data[] = {1, 2, 3, 4};
  std::int8_t dst_data[4];

  ruy::Matrix<std::int8_t> lhs;
  ruy::MakeSimpleLayout(2, 2, ruy::Order::kRowMajor, lhs.mutable_layout());
  lhs.set_data(lhs_data);
  ruy::Matrix<std::int8_t> rhs;
  ruy::MakeSimpleLayout(2, 2, ruy::Order::kColMajor, rhs.mutable_layout());
  rhs.set_data(rhs_data);
  ruy::Matrix<std::int8_t> dst;
  ruy::MakeSimpleLayout(2, 2, ruy::Order::kColMajor, dst.mutable_layout());
  dst.set_data(dst_data);

  ruy::MulParams<std::int32_t, std::int8_t> mul_params;
  ruy::Mul(lhs, rhs, mul_params, context, &dst);

  std::cout << "Example Mul, int8 quantized with per-channel multipliers\n";
  std::cout << "LHS:\n" << lhs;
  std::cout << "RHS:\n" << rhs;
  std::cout << "Result:\n" << dst << "\n";
}
```

**Comment by bjacob** [comment]
The result is zero because the quantization multiplier, in `mul_params`, is left with its default value of zero, effectively multiplying all result accumulators by zero before writing the output. Compare your code to the example code, where the [multiplier is set](https://github.com/google/ruy/blob/master/example/example.cc#L120-L121).  To see the 'specification' of what `ruy::Mul` does, check out [ReferenceMul](https://github.com/google/ruy/blob/master/ruy/reference_mul.h).
